### ISSUE TITLE
软件报毒

### ISSUE THREAD

**Issue by lxfly2000** [flydoos/WinASAR#1]
https://www.virustotal.com/gui/file/60e2a47729c6b1fd6b6223f24dbe11eb0d0fa77240a6473ba995701340784ad3
**报毒率30/74**
放到Github上不开源，软件还要管理员权限，什么成分我就不说了噢

**Comment by flydoos** [comment]
> https://www.virustotal.com/gui/file/60e2a47729c6b1fd6b6223f24dbe11eb0d0fa77240a6473ba995701340784ad3
> **报毒率30/74**
> 放到Github上不开源，软件还要管理员权限，什么成分我就不说了噢

1、GitHub除了开源，还可以分享资料，分享软件，诸如：996，xxx排行榜……
2、但凡你是做过软件的，即便你一行代码不写，直接编译exe，都会被误报，所以readme写了，要添加信任白名单
3、这个软件加壳了，所以误报几率会增大，但是绝对安全。如果你觉得不安全，那你别用就是了
PS：这种问题本不想解释，可惜什么人都有

**Comment by flydoos** [comment]
只要不买一年几千块的数字签名，就几乎没有不报毒，即便一开始不报毒，发布半年后绝对逃不掉

**Comment by F11st** [comment]
解压程序需要管理员启动，嘿嘿嘿你懂得

**Comment by flydoos** [comment]
> 解压程序需要管理员启动，嘿嘿嘿你懂得

不要把无知当聪明，因为如果.asar文件是在C盘的话，必须有管理员权限才能打开，所以程序设置了需要管理员启动。你可以自己反编译，看看是否有非法操作，绝对没有！！！

**Comment by Anonymous220623** [comment]
> > 解压程序需要管理员启动，嘿嘿嘿你懂得
> 
> 不要把无知当聪明，因为如果.asar文件是在C盘的话，必须有管理员权限才能打开，所以程序设置了需要管理员启动。你可以自己反编译，看看是否有非法操作，绝对没有！！！


> > https://www.virustotal.com/gui/file/60e2a47729c6b1fd6b6223f24dbe11eb0d0fa77240a6473ba995701340784ad3
> > **报毒率30/74**
> > 放到Github上不开源，软件还要管理员权限，什么成分我就不说了噢
> 
> 1、GitHub除了开源，还可以分享资料，分享软件，诸如：996，xxx排行榜…… 2、但凡你是做过软件的，即便你一行代码不写，直接编译exe，都会被误报，所以readme写了，要添加信任白名单 3、这个软件加壳了，所以误报几率会增大，但是绝对安全。如果你觉得不安全，那你别用就是了 PS：这种问题本不想解释，可惜什么人都有

这是脱壳后的程序文件，大家可以自行反编译（加壳工具：.NET Reactor；脱壳工具：.NET Reactor Slayer）：

https://mega.nz/file/GFAzHbRD#2pTzUyW2GSZnRa9Ta-nFa0tS6p1Muu3IOZew3LxcTtQ

但是由于文件中没有调试信息，所有的 .NET 反编译器只能复现程序逻辑，无法还原程序内部变量名称。

**Comment by link-fgfgui** [comment]
读取不需要管理员权限

**Comment by flydoos** [comment]
你的软件难道从来不安装到C盘？读取C盘的时候，不需要管理员权限？

**Comment by link-fgfgui** [comment]
<img width="1202" height="952" alt="Image" src="https://github.com/user-attachments/assets/ba01e8b8-0f48-4c58-8ebf-fec65173c062" />

**Comment by link-fgfgui** [comment]
> 你的软件难道从来不安装到C盘？读取C盘的时候，不需要管理员权限？

你的系统上需要管理员权限才能读取吗，我很好奇
测试代码：
```powershell
try {
    $stream = [System.IO.File]::OpenRead("C:\path\to\your\file.txt")
    $stream.Close()
    Write-Host "拥有读取权限" -ForegroundColor Green
} catch {
    Write-Host "没有读取权限: $_" -ForegroundColor Red
}
```

**Comment by flydoos** [comment]
WinASAR 只是读取的软件吗？你可以编辑，需要重新写入的……不再解释，有疑虑的，直接删除软件
（难道说，你改了一半，保存的时候再跟你说没权限报错？所以，这个软件启动的时候就要管理员运行~~）

**Comment by link-fgfgui** [comment]
1. 你的言论改变了，之前你说的是不能读取，这是你的知识不足还是狡辩？
2. 你完全可以写入到%TEMP%，桌面，甚至%APPDATA%和%LOCALAPPDATA%，重新写入到Program Files本来就不安全
3. 如果一定要写入原路径，你可以在写入的时候才申请提权，遵循最小权限原则
4. 没有任何一款压缩软件要求必须管理员权限才能运行，指定需要权限的目录时用户可以手动提权
5. 这不是开源软件，如果这是开源软件，而您不知道怎么实现，我可以给您提PR，可惜没有这个机会
6. 我理解您为这个软件投入了时间和精力最后免费放给大家用还提供有限的支持，我对此深表感激，但是我只是依据我的知识提供一些信息，了解这些信息对您也是有益无害的

**Comment by flydoos** [comment]
1、我不是抠字眼的人，软件读取/写入，在我的口述里面是一样的
2、WinASAR 读取之后，需要解压。也可以支持重新编辑，权限就是要完整，因为这是软件的基础功能
3、你有本事就自己反编译看，绝对是没有任何套路的软件，绝对纯洁。也没有隐藏任何东西，连特么广告都没有
4、我遵循的是，软件给自己用，然后顺便分享的原则。如果你觉得有风险，就删除，我不想接受任何质疑

**Comment by link-fgfgui** [comment]
> （难道说，你改了一半，保存的时候再跟你说没权限报错？所以，这个软件启动的时候就要管理员运行~~）

是的，市面上99%的压缩软件都是这样的

**Comment by flydoos** [comment]
> > （难道说，你改了一半，保存的时候再跟你说没权限报错？所以，这个软件启动的时候就要管理员运行~~）
> 
> 是的，市面上99%的压缩软件都是这样的

**你这个建议已采纳~~**

WinASAR 文件管理工具 2.1.0（WinASAR）
更新日志：2026-08-05

1、优化 ASAR 压缩/解压性能，速度提升数倍（修复海量小文件极慢问题，例如：7500个小文件解压从 62 秒降至约 3.5 秒）
2、此前总有人居心叵测，说WinASAR程序有问题，原因是杀软误报以及需要管理员权限运行（其实小编开发的所有程序，都是默认管理员运行，因为读写C盘文件的时候，有些时候确实需要管理员权限，小编为了省事默认管理员运行，代码也是复用的）。为了避免还有有人拿这个说事，本次取消管理员运行，改为权限不足时按需提示，普通用户可直接运行，仅当后续操作权限不足时再提示以管理员身份运行

下载地址：https://www.wuleba.com/?p=2611
